---
- name: "Guardar configuraciones del equipo"
  hosts: all
  gather_facts: no
  
  tasks:
    - name: "Obtener respaldo"
      ios_config:
        save_when: modified
        backup: yes
        backup_options:
          filename: "{{ inventory_hostname }}"